version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: "db_dev"
    env_file:
      - .env.dev
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data_dev:/var/lib/mysql
    profiles:
      - dev
    networks:
      - dev_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      # dockerfile: Dockerize
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.dev
    ports:
      - "8888:8000"
    volumes:
      - .:/app  # Mount the app source code for live reloading
    networks:
      - dev_network
    profiles:
      - dev

  db_test:
    image: mysql:8.0
    container_name: db_test
    env_file:
      - .env.test
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data_test:/var/lib/mysql
    profiles:
      - test
    networks:
      - test_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  tests:
    build:
      context: .
      dockerfile: ./app/tests/Dockerfile
    depends_on:
      db_test:
        condition: service_healthy
    env_file:
      - .env.test
    volumes:
      - .:/app
    networks:
      - test_network
    profiles:
      - test

networks:
  dev_network:
    driver: bridge
  test_network:
    driver: bridge

volumes:
  db_data_dev:
  db_data_test:
